### PR TITLE
Core/automate-deployment

### PR DESCRIPTION
**Pull request by wizlif**

### CODE REVIEW

**Review by Xazin — APPROVED** [review]

**Comment by Xazin** [comment]
Btw, because you're on a fork the deploy to widgetbook will fail.

**Comment by wizlif** [comment]
> Btw, because you're on a fork the deploy to widgetbook will fail.

Is there a way to skip it for P.Rs and only run it for master or is this by design.

**Comment by Xazin** [comment]
> > Btw, because you're on a fork the deploy to widgetbook will fail.
> 
> Is there a way to skip it for P.Rs and only run it for master or is this by design.

It's by design, as it also allows to preview how widgets look from a PR, so designers would be able to catch mistakes before it would be merged.

**Comment by dromerolovo** [comment]
@wizlif I need to catch up on this. I haven't check it out yet

**Pull request merged**
